services:
  postgres:
    image: postgres:17
    container_name: booking_system_db
    environment:
      POSTGRES_DB: booking_system
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U booking_user -d booking_system"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: