spring:
  datasource:
      url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT:5432}/${POSTGRES_DB}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

  flyway:
    enabled: true

logging:
  level:
    org.flywaydb: DEBUG
