spring:
    application:
        name: booking-system

# spring:
#   sql:
#     init:
#       mode: always
#       platform: h2
#   datasource:
#     initialization-mode: always

    h2:
        console:
            enabled: true
            path: /h2-console

    datasource:
        url: jdbc:h2:file:~/bsdb-local
        username: sa
        password: ""
        driverClassName: org.h2.Driver

    jpa:
        hibernate:
            ddl-auto: create
        show-sql: false
        properties:
            hibernate:
                format_sql: false

logging:
    level:
        com.acs.bookingsystem: DEBUG
        org.springframework.security: DEBUG
        org.springframework.web: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
    secret:
        key: OOVIh6cWzG1n8/g4u2vmpcSxkbZB+DTJ8V0Hq9d4K6g=



# custom config

schedule:
    weekday:
        opening: "09:00"
        closing: "19:00"
    saturday:
        opening: "09:30"
        closing: "19:30"

    sunday:
        opening: "11:00"
        closing: "17:00"

email:
    sender:
        address: testingemailjavamail@gmail.com
        password: ymersplyzlntalvf

    smtp:
        server: smtp.gmail.com
        port: 465

    template:
        invitation:
            subject: "Invitation to Join the ACS Booking System"
            body: |
                Dear User,
                
                We are pleased to inform you that your email address has been whitelisted and you now have access to our ACS Booking System!
                
                To get started, please click the link below to register and set up your account:
                
                {registrationLink}
                
                If you have any questions or need assistance, feel free to contact our support team.
                
                Best regards,
                The ACS Team

        resetPassword:
            subject: "Reset Your ACS Booking System Password"
            body: |
                Dear User,
                
                You requested a password reset. Your new password is:
                
                {password}
                
                Please change your password after logging in.
                
                If you did not request this, please contact support immediately.
                
                Best regards,
                The ACS Team
