name: Pull Request CI/CD flow for booking-system

on:
  pull_request:
    branches: [ "master" ]

jobs:
  maven_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install