name: Push to Master CI/CD flow for booking-system

on:
  push:
    branches: [ "master" ]

jobs:
  build_push_docker:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install

      - name: Build & Push Docker image
        if: github.event_name == 'push'
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: brunamoura/booking-system-image
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}